import mongoose from 'mongoose';

const tradeSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  tradeDate: { type: Date, default: Date.now },
  tradingSession: String,
  marketCondition: String,
  marketType: String,
  symbol: String,
  strikePrice: Number,
  optionType: String,
  expiryDate: String,
  direction: String,
  directionCorrect: Boolean,
  analysisCorrect: Boolean,
  quantity: Number,
  entryPrice: Number,
  exitPrice: Number,
  partialExits: [{ price: Number, quantity: Number }],
  stopLoss: Number,
  target: Number,
  riskAmount: Number,
  brokerage: Number,
  charges: Number,
  customTags: [String],
  entryScore: Number,
  exitScore: Number,
  followedPlan: Boolean,
  earlyEntry: Boolean,
  lateEntry: Boolean,
  revengeTrade: Boolean,
  fomoTrade: Boolean,
  overtrading: Boolean,
  emotionBefore: String,
  emotionDuring: String,
  emotionAfter: String,
  emotionNotes: String,
  disciplineScore: Number,
  confidenceLevel: Number,
  stressLevel: Number,
  whyTradeTaken: String,
  whatWentRight: String,
  whatWentWrong: String,
  lessonsLearned: String,
  repeatableSetup: Boolean,
  pointsCaptured: String,
  rulesFollowed: Boolean,
  averageEntryPrice: Number,
  averageExitPrice: Number,
  grossPnL: Number,
  netPnL: Number,
  roi: Number,
  rMultiple: Number,
  riskRewardRatio: Number,
  tradeQualityScore: Number,
  winLossStatus: String,
  beforeEntryImage: String,
  duringTradeImage: String,
  exitImage: String,
}, {
  timestamps: true,
});

export default mongoose.model('Trade', tradeSchema);
